vich_uploader:
  # cette commande spécifie la configuration du driver de la base de données
  db_driver: orm

  metadata:
    type: attribute

  # Ces mappings indiquent au composant où les fichiers doivent être téléchargés et quels chemins doivent être utilisés pour les afficher dans l'application
  mappings:
    images:
      uri_prefix: /images
      upload_destination: "%kernel.project_dir%/public/images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      # directory_namer:
      #   service: App\Namer\MediaDirectoryNamer
      inject_on_load: true
    pdf:
      uri_prefix: /pdf
      upload_destination: "%kernel.project_dir%/public/pdf"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: true
    media_file:
      uri_prefix: /uploads/media
      upload_destination: "%kernel.project_dir%/public/uploads/media"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
